version: '3'
services:
  #This is our main database container, we are listening on 8083 for administrative purposes and 8086 to talk to
  #the database API
  influxdb:
    image: influxdb:1.2.3
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - "./influxdb.conf:/etc/influxdb/influxdb.conf"
  #This is the telegraf container, it will be used primarily as a stastd interface listening on 8125
  telegraf:
    image: telegraf:1.2.1
    volumes:
      - "./telegraf.conf:/etc/telegraf/telegraf.conf"
    ports:
      - "8125:8125/udp"
    depends_on:
      - "influxdb"
  #This is the grafana dashboard container, listening on port 3000
  grafana:
    image: grafana/grafana:4.2.0
    ports:
      - "3000:3000"
  #This will be a simulated server that sends OS Performance stats to InfluxDB, we will scale this out in the demo
  #to simulate multiple OS's
  test_client:
    image: telegraf:1.2.1
    volumes:
      - "./telegraf.conf:/etc/telegraf/telegraf.conf"
    depends_on:
      - "telegraf"
  #This container simply loops and sends counters to the statsd interface.  we will scale this out in the demo as well
  test_counter:
    image: davidasnider/alpine-nc:20170516
    volumes:
      - "./counter.sh:/counter.sh"
    entrypoint: /counter.sh
  #This container simply loops and sends random numbers (1-100) as a gauge counter every 10 seconds. Will scale during
  #the demo
  test_gauge:
    image: davidasnider/alpine-nc:20170516
    environment:
      - SLEEP=10
    volumes:
      - "./gauge.sh:/gauge.sh"
    entrypoint: /gauge.sh
  #This container simply loops and sensd random numbers (1-100) as a timer/histogram every 10 seconds.  We will scale
  #during the demo
  test_timing:
    image: davidasnider/alpine-nc:20170516
    environment:
      - SLEEP=1
    volumes:
      - "./timing.sh:/timing.sh"
    entrypoint: /timing.sh

